apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo-hello
  labels:
    app: nginxdemo-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxdemo-hello
  template:
    metadata:
      labels:
        app: nginxdemo-hello
    spec:
      containers:
      - name: nginxdemo-hello
        image: nginxdemos/hello:plain-text
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
