apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  providerRef:
    name: default
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.large
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - ap-northeast-2a
    - ap-northeast-2b
    - ap-northeast-2c
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
